# NumPy Fundamentals

A structured walkthrough of core NumPy concepts: creating arrays, inspecting
their attributes, indexing, aggregation, array-creation helpers, broadcasting,
comparisons, reshaping, and the most commonly used mathematical functions
(each with a worked example).

**Library used:** `numpy`


In [1]:
import numpy as np

## 1. Creating Arrays

NumPy arrays (`ndarray`) are the core data structure of the library. They can be created from Python lists using `np.array()`.

In [2]:
# A 1-D array (vector)
arr_1d = np.array([12, 13, 14, 15])
arr_1d, type(arr_1d)

(array([12, 13, 14, 15]), numpy.ndarray)

### Python lists vs. NumPy arrays

Python's `+` and `*` operators behave very differently on lists compared to arrays:
- On a **list**, `+` concatenates and `*` repeats.
- On a NumPy **array**, `+` and `*` are element-wise (vectorized) math operations.

In [3]:
list_a = [12, 13, 14, 15]
list_b = [5, 6, 7, 8, 9]

concatenated = list_a + list_b   # concatenation, NOT addition
repeated = list_a * 2            # repeats the list twice

concatenated, repeated

([12, 13, 14, 15, 5, 6, 7, 8, 9], [12, 13, 14, 15, 12, 13, 14, 15])

In [4]:
array_a = np.array([1, 2, 3, 4, 5])
array_b = np.array([6, 7, 8, 9, 10])

elementwise_sum = array_a + array_b   # element-wise addition
scaled = array_a * 2                  # element-wise multiplication

elementwise_sum, scaled

(array([ 7,  9, 11, 13, 15]), array([ 2,  4,  6,  8, 10]))

**Note on mixing lists and arrays:** when a plain list is combined with a NumPy array using `+`, NumPy converts the list to an array first, so the result is element-wise addition — *not* concatenation. This only works if both are the same length.

In [5]:
python_list = [12, 3, 1]
numpy_array = np.array([4, 5, 6])

mixed_result = python_list + numpy_array   # list is coerced to an array
mixed_result

array([16,  8,  7])

## 2. Array Attributes

Renamed from the original `dih` to **`matrix_2d`** for clarity — the name now reflects what the variable actually holds (a 2-dimensional array).

In [6]:
matrix_2d = np.array([[1, 2, 3, 4, 5],
                       [6, 7, 8, 9, 10]])
matrix_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
matrix_2d.ndim   # number of dimensions (axes)

2

In [8]:
matrix_2d.shape  # size along each dimension: (rows, columns)

(2, 5)

In [9]:
matrix_2d.dtype  # data type of the elements

dtype('int64')

In [10]:
matrix_2d.size   # total number of elements (rows * columns)

10

### Indexing

In [11]:
matrix_2d[1]     # the second row (index 1)

array([ 6,  7,  8,  9, 10])

### Aggregation methods

These summarize all elements of the array.

In [12]:
matrix_2d.sum()   # sum of all elements

np.int64(55)

In [13]:
matrix_2d.max()   # largest element

np.int64(10)

In [14]:
matrix_2d.mean()  # average of all elements

np.float64(5.5)

In [15]:
matrix_2d.min()   # smallest element

np.int64(1)

In [16]:
matrix_2d.std()   # standard deviation of all elements

np.float64(2.8722813232690143)

## 3. Array-Creation Functions

NumPy provides several convenience functions for building arrays without typing out every element by hand.

In [17]:
zeros_list = [0] * 12   # plain Python list of zeros, for comparison
zeros_list

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [18]:
zeros_array = np.zeros(12)   # 1-D array of zeros (float64 by default)
zeros_array.dtype, zeros_array

(dtype('float64'), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

In [19]:
# A 3-D array of zeros: 7 "layers" of 4x4 grids, stored as integers
zeros_3d = np.zeros((7, 4, 4), dtype=int)
zeros_3d.shape, zeros_3d

((7, 4, 4),
 array([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],
 
        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],
 
        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],
 
        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],
 
        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],
 
        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],
 
        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]]))

In [20]:
# np.full(shape, fill_value) creates an array pre-filled with a constant
filled_array = np.full((4, 7), 6)
filled_array

array([[6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6]])

In [21]:
# np.arange(start, stop, step) -> stop is EXCLUSIVE
range_array = np.arange(2, 8, 1)
range_array

array([2, 3, 4, 5, 6, 7])

In [22]:
# np.linspace(start, stop, num) -> stop is INCLUSIVE; returns `num` evenly spaced values
evenly_spaced = np.linspace(2, 8, 8)
evenly_spaced

array([2.        , 2.85714286, 3.71428571, 4.57142857, 5.42857143,
       6.28571429, 7.14285714, 8.        ])

In [23]:
# np.random.random(shape) -> array of random floats in [0.0, 1.0)
random_array = np.random.random((4, 8))
random_array.shape

(4, 8)

## 4. Finding Extremes: `max`/`min` vs. `argmax`/`argmin`

- `np.max` / `np.min` return the **value**.
- `np.argmax` / `np.argmin` return the **index** at which that value occurs.

In [24]:
sample_values = np.array([1, 5, 6, 7, 8, 45, 64, 46])

largest_value = np.max(sample_values)     # value
largest_index = np.argmax(sample_values)  # index of that value

largest_value, largest_index

(np.int64(64), np.int64(6))

In [25]:
smallest_value = np.min(sample_values)
smallest_index = np.argmin(sample_values)

smallest_value, smallest_index

(np.int64(1), np.int64(0))

## 5. Mathematical Functions

General pattern: `np.functionname(operand)` or `np.functionname(op1, op2)`. Every function below is shown on both a **single value** and a **whole array** (NumPy applies these element-wise automatically).

### 5.1 Exponentials & Logarithms

In [26]:
np.log(10)     # natural log (base e) of 10

np.float64(2.302585092994046)

In [27]:
np.exp(2)      # e raised to the power 2

np.float64(7.38905609893065)

In [28]:
np.sqrt(6)     # square root of 6

np.float64(2.449489742783178)

In [29]:
perfect_squares = np.array([1, 4, 9, 25, 36, 49, 64, 81, 100])
np.sqrt(perfect_squares)   # sqrt applied element-wise to the whole array

array([ 1.,  2.,  3.,  5.,  6.,  7.,  8.,  9., 10.])

In [30]:
np.log2(8)     # log base 2

np.float64(3.0)

In [31]:
np.log10(1000)  # log base 10

np.float64(3.0)

In [32]:
np.power(2, 5)   # 2 raised to the power 5

np.int64(32)

In [33]:
np.power(np.array([1, 2, 3, 4]), 2)   # element-wise squaring

array([ 1,  4,  9, 16])

### 5.2 Basic Arithmetic Functions (equivalent to `+ - * /`)

In [34]:
base_values = np.array([1, 4, 9, 25, 36, 49, 64, 81, 100])

added        = base_values + 1     # np.add(base_values, 1)
subtracted   = base_values - 3     # np.subtract(base_values, 3)
multiplied   = base_values * 12    # np.multiply(base_values, 12)
divided      = base_values / 7     # np.divide(base_values, 7)

added, subtracted, multiplied, divided

(array([  2,   5,  10,  26,  37,  50,  65,  82, 101]),
 array([-2,  1,  6, 22, 33, 46, 61, 78, 97]),
 array([  12,   48,  108,  300,  432,  588,  768,  972, 1200]),
 array([ 0.14285714,  0.57142857,  1.28571429,  3.57142857,  5.14285714,
         7.        ,  9.14285714, 11.57142857, 14.28571429]))

In [35]:
np.add(5, 3), np.subtract(5, 3), np.multiply(5, 3), np.divide(5, 3)

(np.int64(8), np.int64(2), np.int64(15), np.float64(1.6666666666666667))

### 5.3 Trigonometric Functions

In [36]:
angle_rad = np.pi / 2   # 90 degrees in radians
np.sin(angle_rad), np.cos(angle_rad), np.tan(np.pi / 4)

(np.float64(1.0),
 np.float64(6.123233995736766e-17),
 np.float64(0.9999999999999999))

In [37]:
angles = np.array([0, np.pi / 2, np.pi])
np.sin(angles)   # applied element-wise

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

### 5.4 Rounding Functions

In [38]:
value = 4.567
np.round(value, 2), np.floor(value), np.ceil(value)

(np.float64(4.57), np.float64(4.0), np.float64(5.0))

In [39]:
decimals = np.array([1.2, 2.7, -3.5, 4.49])
np.round(decimals), np.floor(decimals), np.ceil(decimals)

(array([ 1.,  3., -4.,  4.]),
 array([ 1.,  2., -4.,  4.]),
 array([ 2.,  3., -3.,  5.]))

### 5.5 Absolute Value & Modulo

In [40]:
np.abs(-7), np.abs(np.array([-3, -1, 2, -8]))

(np.int64(7), array([3, 1, 2, 8]))

In [41]:
np.mod(10, 3)   # remainder of 10 / 3

np.int64(1)

## 6. Comparison Functions

In [42]:
tt = np.array([3, 4, 5, 6])
td = np.array([3, -1, 4, 6])

np.equal(tt, td)   # element-wise comparison -> boolean array

array([ True, False, False,  True])

In [43]:
tt == td   # same result using the standard operator

array([ True, False, False,  True])

In [44]:
np.array_equal(tt, td)   # True only if ALL elements match (whole-array check)

False

In [45]:
np.greater(tt, td), np.less(tt, td)   # element-wise > and <

(array([False,  True,  True, False]), array([False, False, False, False]))

## 7. Multi-Dimensional Arrays, Broadcasting, and Reshaping

In [46]:
tensor_3d = np.array([[[1, 2, 3, 4], [2, 4, 3, 5], [5, 6, 7, 8], [7, 8, 5, 4]],
                       [[1, 2, 3, 4], [2, 4, 3, 5], [5, 6, 7, 8], [7, 8, 5, 4]]])
tensor_3d.shape, tensor_3d.ndim

((2, 4, 4), 3)

Summing along an axis collapses that dimension:

In [47]:
np.sum(tensor_3d, axis=0)   # sum across the outermost axis (the two "layers")

array([[ 2,  4,  6,  8],
       [ 4,  8,  6, 10],
       [10, 12, 14, 16],
       [14, 16, 10,  8]])

In [48]:
np.sum(tensor_3d, axis=1)   # sum across rows within each layer

array([[15, 20, 18, 21],
       [15, 20, 18, 21]])

**Broadcasting**: NumPy automatically stretches a smaller array to match a larger one's shape when their trailing dimensions are compatible — no explicit loop needed.

In [49]:
matrix_4x4 = np.array([[1, 2, 3, 4],
                        [2, 4, 3, 5],
                        [5, 6, 7, 8],
                        [7, 8, 5, 4]])

matrix_4x4 + [1, 2, 3, 4]   # the 1-D array is broadcast across every row

array([[ 2,  4,  6,  8],
       [ 3,  6,  6,  9],
       [ 6,  8, 10, 12],
       [ 8, 10,  8,  8]])

**Reshaping**: `reshape` rearranges the same elements into a new shape (the total element count must stay the same: 4x4 = 16 = 2x8).

In [50]:
matrix_4x4.reshape(2, 8)

array([[1, 2, 3, 4, 2, 4, 3, 5],
       [5, 6, 7, 8, 7, 8, 5, 4]])

## Summary

| Category | Functions covered |
|---|---|
| Creation | `np.array`, `np.zeros`, `np.full`, `np.arange`, `np.linspace`, `np.random.random` |
| Attributes | `.ndim`, `.shape`, `.dtype`, `.size` |
| Aggregation | `.sum`, `.max`, `.min`, `.mean`, `.std`, `np.argmax`, `np.argmin` |
| Exponential/Log | `np.exp`, `np.log`, `np.log2`, `np.log10`, `np.sqrt`, `np.power` |
| Arithmetic | `np.add`, `np.subtract`, `np.multiply`, `np.divide` |
| Trigonometric | `np.sin`, `np.cos`, `np.tan` |
| Rounding | `np.round`, `np.floor`, `np.ceil` |
| Other | `np.abs`, `np.mod` |
| Comparison | `np.equal`, `np.array_equal`, `np.greater`, `np.less` |
| Shape ops | `axis`-wise `np.sum`, broadcasting, `.reshape` |
